# Generated by Django 4.2.1 on 2023-05-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu1', models.IntegerField(default=0)),
                ('menu2', models.IntegerField(default=0)),
                ('menu3', models.IntegerField(default=0)),
                ('menu4', models.IntegerField(default=0)),
                ('menu5', models.IntegerField(default=0)),
                ('menu6', models.IntegerField(default=0)),
                ('menu7', models.IntegerField(default=0)),
                ('menu8', models.IntegerField(default=0)),
                ('special_note', models.TextField(blank=True, null=True)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu1', models.IntegerField(default=0)),
                ('menu2', models.IntegerField(default=0)),
                ('menu3', models.IntegerField(default=0)),
                ('menu4', models.IntegerField(default=0)),
                ('menu5', models.IntegerField(default=0)),
                ('menu6', models.IntegerField(default=0)),
                ('menu7', models.IntegerField(default=0)),
                ('menu8', models.IntegerField(default=0)),
                ('special_note', models.TextField(blank=True, null=True)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu1', models.IntegerField(default=0)),
                ('menu2', models.IntegerField(default=0)),
                ('menu3', models.IntegerField(default=0)),
                ('menu4', models.IntegerField(default=0)),
                ('menu5', models.IntegerField(default=0)),
                ('menu6', models.IntegerField(default=0)),
                ('menu7', models.IntegerField(default=0)),
                ('menu8', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
