# Generated by Django 4.2.1 on 2023-05-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_result_special_note_table_special_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='number',
        ),
    ]
